accounts:
  - name: kilian
    coins: ["1000000000motiv", "200000000stake"]
validator:
  name: kilian
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
